{% set name = "canopy-tools" %}
{% set version = "0.3.8" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/canopy_tools-{{ version }}.tar.gz
  sha256: 28ad655bfe7d48bcbc28e0f2381616056724fe9259be5f7ce2b9977a83b4fe92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.0
    - xarray >=2025.3.0
    - numpy >=2.2.0
    - matplotlib-base >=3.10.0
    - typing_extensions >=4.13.0
    - tqdm >=4.67.0
    - cartopy >=0.24.0
    - seaborn >=0.13.0
    - scipy >=1.15.0
    - jenkspy >=0.4.0

test:
  imports:
    - canopy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A python package to analyse LSM and DGVM outputs
  home: https://codebase.helmholtz.cloud/canopy/canopy
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdrienDams
